### PR TITLE
Cast hash64 value to uint64 before doing operations

### LINKED ISSUE #38: Doesn't compile on 32bit
This function created a compile error when trying to build with arm32 (```CGO_ENABLED=0 GOOS=linux GOARCH=arm go build test.go```)
https://github.com/puzpuzpuz/xsync/blob/d5f0f9d5b79c39bf68bf9771f52f477262972f6f/util.go#L18-L24

Following error is shown: 
```
#0 7.331 /go/pkg/mod/github.com/puzpuzpuz/xsync@v1.2.1/util.go:20:24: 0xff51afd7ed558ccd (untyped int constant 18397679294719823053) overflows uintptr
#0 7.331 /go/pkg/mod/github.com/puzpuzpuz/xsync@v1.2.1/util.go:21:24: 0xc4ceb9fe1a85ec53 (untyped int constant 14181476777654086739) overflows uintptr
```

This can likely be fixed by casting the argument to uint64 before performing the operations.

### PR DESCRIPTION
**Pull request by ptrcnull**
Fixes #38

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
Hi,

Thanks for the contribution. I'm afraid that this change is not sufficient. All tests should be passing in 32-bit which is not the case for a number of reasons:
```
$ GOARCH=386 go test .
--- FAIL: TestMap_MissingEntry (0.00s)
panic: unaligned 64-bit atomic operation [recovered]
	panic: unaligned 64-bit atomic operation

goroutine 133 [running]:
testing.tRunner.func1.2({0x813e620, 0x817be18})
	/usr/local/go/src/testing/testing.go:1209 +0x2ab
testing.tRunner.func1(0xbe620f0)
	/usr/local/go/src/testing/testing.go:1212 +0x27d
panic({0x813e620, 0x817be18})
	/usr/local/go/src/runtime/panic.go:1038 +0x1c5
runtime/internal/atomic.panicUnaligned()
	/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Load64(0xbe66004)
	/usr/local/go/src/runtime/internal/atomic/atomic_386.s:225 +0x10
github.com/puzpuzpuz/xsync.(*Map).resizeInProgress(...)
	/home/puzpuzpuz/projects/xsync/map.go:252
github.com/puzpuzpuz/xsync.(*Map).LoadAndDelete(0xbe66000, {0x8152fe5, 0x3})
	/home/puzpuzpuz/projects/xsync/map.go:367 +0x107
github.com/puzpuzpuz/xsync_test.TestMap_MissingEntry(0xbe620f0)
	/home/puzpuzpuz/projects/xsync/map_test.go:59 +0xbb
testing.tRunner(0xbe620f0, 0x815de58)
	/usr/local/go/src/testing/testing.go:1259 +0xe6
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x33a
FAIL	github.com/puzpuzpuz/xsync	0.156s
FAIL
```

**Comment by ptrcnull** [comment]
ah, you're right; i'll try to fix the test failures too

**Comment by ptrcnull** [comment]
(it passes the tests now btw)
```
$ GOARCH=386 go test .
ok  	github.com/puzpuzpuz/xsync	4.828s
```

**Review by puzpuzpuz — APPROVED** [review]
Sorry, I was unavailable for a few days. LGTM. Thanks for the contribution!

**Comment by ohdearaugustin** [comment]
@ptrcnull Thank you for your work (=

**Pull request merged**
